COMMON: &common
  SECRET_KEY: insecure
  SQLALCHEMY_DATABASE_URI: 'sqlite:///dev.db'
  ADMIN_CREDENTIALS: 'admin,password'

  SECURITY_TRACKABLE: True
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'

  SOCIAL_TWITTER:
    consumer_key: 'BvvEnwBSsO9EQJ3y73t2jlAtw'
    consumer_secret: 'k2VnzSEw6AHgt3C0S1rjEiPtEBcbJNQvKT0hEVwv9Q5PSOws44'

  SOCIAL_FACEBOOK:
    consumer_key: '282525155285510'
    consumer_secret: '3affe132dab12abbccc5d5a98d2598eb'
    request_token_params:
      scope: 'email'


DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt
  SOCIAL_APP_URL: http://flask-social-example.herokuapp.com/