COMMON: &common
  SECRET_KEY: insecure
  # SQLALCHEMY_DATABASE_URI: 'sqlite:///dev.db'
  SQLALCHEMY_DATABASE_URI: 'postgres://postgres:postgres@localhost/tedx'
  ADMIN_CREDENTIALS: 'admin,password'

  SECURITY_TRACKABLE: True
  SECURITY_CONFIRM_ERROR_VIEW: '/'
  SECURITY_POST_LOGIN_VIEW: '/'
  SOCIAL_CONNECT_ALLOW_VIEW: '/profile'
  CELERY_BROKER_URL: 'redis://localhost:6379/0'
  CELERY_RESULT_BACKEND: 'redis://localhost:6379/0'


  SOCIAL_TWITTER:
    consumer_key: 'PkGO6dLiwip0Y0zvDEbrSP1cK'
    consumer_secret: 'r2dfffMhxJzEB1gzIjdFcZmrL5IPZm1qt789jyV36M10wJSjgV'

  SOCIAL_FACEBOOK:
    consumer_key: '661404867289872'
    consumer_secret: 'c04a8fa667e55be12c803943e4087cad'
    request_token_params:
      scope: 'email'


DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  DEBUG: True
  SECURITY_PASSWORD_HASH: bcrypt