"""empty message

Revision ID: 240048474e37
Revises: f0a19e30998
Create Date: 2014-09-15 13:48:09.128029

"""

# revision identifiers, used by Alembic.
revision = '240048474e37'
down_revision = 'f0a19e30998'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sex')
    ### end Alembic commands ###
