"""empty message

Revision ID: 2e48174d6e49
Revises: None
Create Date: 2015-03-02 12:19:52.420338

"""

# revision identifiers, used by Alembic.
revision = '2e48174d6e49'
down_revision = '240048474e37'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_subject', sa.String(length=60), nullable=True),
    sa.Column('experiment_log', sa.String(), nullable=True),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiment')
    op.drop_table('file_experiment')
    ### end Alembic commands ###
