"""empty message

Revision ID: 40580ec50dd5
Revises: None
Create Date: 2014-09-05 12:08:05.744942

"""

# revision identifiers, used by Alembic.
revision = '40580ec50dd5'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
