"""empty message

Revision ID: 46b824378e7f
Revises: 5952e8499df8
Create Date: 2015-03-09 16:17:28.781497

"""

# revision identifiers, used by Alembic.
revision = '46b824378e7f'
down_revision = '5952e8499df8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cronotipos', u'user_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronotipos', sa.Column(u'user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    ### end Alembic commands ###
