"""empty message

Revision ID: 520c1485336
Revises: 5abab8e9d1be
Create Date: 2015-03-16 17:43:44.416656

"""

# revision identifiers, used by Alembic.
revision = '520c1485336'
down_revision = '5abab8e9d1be'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronotipos', sa.Column('pregunta_cuanto_duermo_siesta_dia_habil', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('pregunta_cuanto_duermo_siesta_dia_libre', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('pregunta_duermo_siesta_dia_habil', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('pregunta_duermo_siesta_dia_libre', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cronotipos', 'pregunta_duermo_siesta_dia_libre')
    op.drop_column('cronotipos', 'pregunta_duermo_siesta_dia_habil')
    op.drop_column('cronotipos', 'pregunta_cuanto_duermo_siesta_dia_libre')
    op.drop_column('cronotipos', 'pregunta_cuanto_duermo_siesta_dia_habil')
    ### end Alembic commands ###
