"""empty message

Revision ID: 5261344d5bfb
Revises: 40580ec50dd5
Create Date: 2014-09-05 12:08:43.139721

"""

# revision identifiers, used by Alembic.
revision = '5261344d5bfb'
down_revision = '40580ec50dd5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('study', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('twitter_handle', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('work', sa.String(length=255), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'work')
    op.drop_column('users', 'twitter_handle')
    op.drop_column('users', 'study')
    op.drop_column('users', 'name')
    op.drop_column('users', 'age')
    ### end Alembic commands ###
