"""empty message

Revision ID: 5952e8499df8
Revises: 2e48174d6e49
Create Date: 2015-03-09 15:02:32.131455

"""

# revision identifiers, used by Alembic.
revision = '5952e8499df8'
down_revision = '2e48174d6e49'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table(u'file_experiment')
    op.add_column('cronotipos', sa.Column('fecha_nacimiento', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('genero', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('mail_up', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('porque_elegiste_turno', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('trabajas', sa.String(), nullable=True))
    op.add_column('cronotipos', sa.Column('turno_analisis', sa.String(), nullable=True))
    op.drop_column('experiment', u'created_date')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column(u'created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('cronotipos', 'turno_analisis')
    op.drop_column('cronotipos', 'trabajas')
    op.drop_column('cronotipos', 'porque_elegiste_turno')
    op.drop_column('cronotipos', 'mail_up')
    op.drop_column('cronotipos', 'genero')
    op.drop_column('cronotipos', 'fecha_nacimiento')
    op.create_table(u'file_experiment',
    sa.Column(u'id', sa.INTEGER(), server_default="nextval('file_experiment_id_seq'::regclass)", nullable=False),
    sa.Column(u'experiment_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column(u'created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint(u'id', name=u'file_experiment_pkey')
    )
    ### end Alembic commands ###
