"""empty message

Revision ID: 5abab8e9d1be
Revises: 46b824378e7f
Create Date: 2015-03-09 16:44:20.872880

"""

# revision identifiers, used by Alembic.
revision = '5abab8e9d1be'
down_revision = '46b824378e7f'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronotipos', sa.Column('comments', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cronotipos', 'comments')
    ### end Alembic commands ###
