"""empty message

Revision ID: c63e675e6c6
Revises: None
Create Date: 2015-01-30 16:58:36.216393

"""

# revision identifiers, used by Alembic.
revision = 'c63e675e6c6'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_subject', sa.String(length=60), nullable=True),
    sa.Column('experiment_log', sa.String(), nullable=True),
    sa.Column('experiment_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=120), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('twitter_handle', sa.String(length=255), nullable=True),
    sa.Column('work', sa.String(length=255), nullable=True),
    sa.Column('study', sa.String(length=255), nullable=True),
    sa.Column('age', sa.String(length=255), nullable=True),
    sa.Column('sex', sa.String(length=255), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('current_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=100), nullable=True),
    sa.Column('current_login_ip', sa.String(length=100), nullable=True),
    sa.Column('login_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('connections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider_id', sa.String(length=255), nullable=True),
    sa.Column('provider_user_id', sa.String(length=255), nullable=True),
    sa.Column('access_token', sa.String(length=255), nullable=True),
    sa.Column('secret', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('profile_url', sa.String(length=512), nullable=True),
    sa.Column('image_url', sa.String(length=512), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cronotipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('pregunta_1', sa.String(), nullable=True),
    sa.Column('pregunta_2', sa.String(), nullable=True),
    sa.Column('pregunta_3', sa.String(), nullable=True),
    sa.Column('pregunta_4', sa.String(), nullable=True),
    sa.Column('pregunta_5', sa.String(), nullable=True),
    sa.Column('pregunta_6', sa.String(), nullable=True),
    sa.Column('pregunta_7', sa.String(), nullable=True),
    sa.Column('pregunta_8', sa.String(), nullable=True),
    sa.Column('pregunta_9', sa.String(), nullable=True),
    sa.Column('pregunta_10', sa.String(), nullable=True),
    sa.Column('pregunta_11', sa.String(), nullable=True),
    sa.Column('pregunta_12', sa.String(), nullable=True),
    sa.Column('pregunta_13', sa.String(), nullable=True),
    sa.Column('pregunta_14', sa.String(), nullable=True),
    sa.Column('pregunta_15', sa.String(), nullable=True),
    sa.Column('pregunta_16', sa.String(), nullable=True),
    sa.Column('pregunta_17', sa.String(), nullable=True),
    sa.Column('pregunta_18', sa.String(), nullable=True),
    sa.Column('pregunta_19', sa.String(), nullable=True),
    sa.Column('pregunta_20', sa.String(), nullable=True),
    sa.Column('pregunta_21', sa.String(), nullable=True),
    sa.Column('pregunta_22', sa.String(), nullable=True),
    sa.Column('pregunta_23', sa.String(), nullable=True),
    sa.Column('pregunta_24', sa.String(), nullable=True),
    sa.Column('pregunta_25', sa.String(), nullable=True),
    sa.Column('pregunta_26', sa.String(), nullable=True),
    sa.Column('pregunta_27', sa.String(), nullable=True),
    sa.Column('result', sa.String(), nullable=True),
    sa.Column('result_type', sa.String(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roles_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], )
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roles_users')
    op.drop_table('cronotipos')
    op.drop_table('connections')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('experiment')
    ### end Alembic commands ###
