"""empty message

Revision ID: f0a19e30998
Revises: a72808072d8
Create Date: 2014-09-10 19:56:59.218711

"""

# revision identifiers, used by Alembic.
revision = 'f0a19e30998'
down_revision = 'a72808072d8'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cronotipos', sa.Column('date', sa.DateTime(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cronotipos', 'date')
    ### end Alembic commands ###
